### ISSUE TITLE
Catch duplicate _id error

### ISSUE THREAD

**Issue by dimokgit** [dimokgit/HedgeHog#163]

**Comment by dimokgit** [comment]
https://dimok.loggly.com/search#terms=&from=2018-08-09T07:25:11.947Z&until=2018-08-09T13:25:11.947Z&source_group=&event=409ffeb2-9bd6-11e8-803c-06e403ed47d2,1533820515398,137531133144334002
[Log](https://dimok.loggly.com/search#terms=&from=2018-08-09T07:25:11.947Z&until=2018-08-09T13:25:11.947Z&source_group=&event=409ffeb2-9bd6-11e8-803c-06e403ed47d2,1533820515398,137531133144334002)
{ DatabaseName = forex }
   at HedgeHog.MongoDB.ForexDbContext.SaveChanges() in C:\Dev\Projects\Mongo\Mongo.EF\Mongo.EF\ForexDbContext.cs:line 58
   at HedgeHog.Alice.Store.GlobalStorage.UseForexMongo(Action`1 action, Boolean save, Action onSave) in E:\Users\dimon\Documents\GitHubVisualStudio\HedgeHog\HedgeHog.Alice.Store\GlobalStorage.cs:line 151
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Blueshift.EntityFrameworkCore.MongoDB.Storage.MongoDbDatabase.<SaveChanges>b__5_1(IGrouping`2 grouping)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Sum(IEnumerable`1 source)
   at Blueshift.EntityFrameworkCore.MongoDB.Storage.MongoDbDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at HedgeHog.MongoDB.ForexDbContext.SaveChanges() in C:\Dev\Projects\Mongo\Mongo.EF\Mongo.EF\ForexDbContext.cs:line 56
A bulk write operation resulted in one or more errors.
  E11000 duplicate key error index: forex.trades.$_id_ dup key: { : "E2CQ8 C2860:1533771082" }
   at MongoDB.Driver.MongoCollectionImpl`1.BulkWrite(IClientSessionHandle session, IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.<>c__DisplayClass23_0.<BulkWrite>b__0(IClientSessionHandle session)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSession[TResult](Func`2 func, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.BulkWrite(IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at Blueshift.EntityFrameworkCore.MongoDB.Storage.MongoDbDatabase.SaveChanges[TEntity](IEnumerable`1 entries)
Add to Search
timestamp:2018-08-09T09:15:15.3980048-04:00
